# Generated by Django 4.1.6 on 2023-04-01 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='avatars', verbose_name='Аватар'),
        ),
    ]
